image: python:3.10-slim

stages:
  - test

API tests:
    stage: test
    script:
        - pip install -r req.txt
        - python3 -m pytest --alluredir=allure_report tests/

    artifacts:
        paths:
          - allure_report/*
